language: python
python:
  - "3.9"

services:
  - postgresql

env:
  global:
  - DJANGO_SETTINGS_MODULE=mysite.settings
  - COVERALLS_REPO_TOKEN=dBx1hvfRo10NfRMeubGZSO0b2zX799fcNYkj

install:
  - pip install -r requirements.txt


after_success:
  - coverage run --source='.' manage.py test
  - coveralls

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "mysite"
  env: "my-env"
  bucket_name: "*"
  on:
    branch: main

script:
  - black --check .
  - flake8 .
  - python manage.py test

